### ISSUE TITLE
Getting Error 102-2160

### ISSUE THREAD

**Issue by WizardNight7718** [PretendoNetwork/Inkay#10]
I have tried to use Pretendo, but it seems to not be working correctly.

102-2160 (Wii U)
Wii U support code detected
Information is WIP and may be missing/incorrect
Module Name
ACT
​
Module Description
Accounts

Error Name 
HTTP_SSL_CACERT
​
​Error Description
Missing description

Fix
Missing fix

Console dialog message
Missing message

**Comment by ashquarky** [comment]
When does that happen? When logging in or creating an account on the menu? Or opening the Miiverse applet?
Are you using Inkay from the releases tab or the bleeding edge build? Which commit (if you know)?

**Comment by WizardNight7718** [comment]
I was trying to create a PNID on the Wii U, and could not get any farther than "Do you want to link your existing ID to this Wii U?" I am using Inkay bleeding edge build (https://github.com/PretendoNetwork/Inkay/actions/runs/4635811241)

**Comment by WizardNight7718** [comment]
I have a video of the error.
https://drive.google.com/file/d/1WCr-sR9rF8-vtaFbq49RifCyIljOAOyh/view?usp=sharing

**Comment by WizardNight7718** [comment]
I hope I can fix this, some how

**Comment by theDSi2homebrewGuy** [comment]
same issue for me

**Comment by jack4455667788** [comment]
It's bloopair.

The two aren't playing nice together.

**Comment by WizardNight7718** [comment]
I'll test it out when I get home 👍

**Comment by jonbarrow** [comment]
> Same thing happens in tiramisu using nimble.

It should be noted that Tiramisu and the legacy Nimble HB are no longer supported by us

**Comment by WizardNight7718** [comment]
> It's bloopair.
> 
> The two aren't playing nice together.
> 
> Same thing happens in tiramisu using nimble.

Error still occurs even with removal of bloopair

**Comment by jack4455667788** [comment]
> > It's bloopair.
> > The two aren't playing nice together.
> > Same thing happens in tiramisu using nimble.
> 
> Error still occurs even with removal of bloopair

Apologies for the red herring. I had read a report where a user found they couldn't use pretendo when bloopair was enabled and had convinced myself of the same thing (i didn't realize that the nintendo login servers for wiiu were still up - so when I thought pretendo was working it was really just connecting me to the nintendo servers which are still online. In fact, pretendo never worked - in tiramisu with nimble, where it did nothing or in aroma with the latest inkay where it causes the 2160 error)

I tried causing the 2160 in tiramisu and was unsuccessful (with or without bloopair).  It seems no servers are being changed by nimble.

**Comment by jack4455667788** [comment]
> > Same thing happens in tiramisu using nimble.
> 
> It should be noted that Tiramisu and the legacy Nimble HB are no longer supported by us

That's too bad. Tiramisu is required for a lot of good stuff, including MK8 Ultimate.  A working CTGP-U would be a fantastic thing to have.

Sorry for the bad lead. Nimble does not function (except to cause wups, and hence MK8 Ultimate, to blackscreen) in tiramisu, and inkay causes 2160 for me as well as the OP.  Are we really the only ones affected?  If so I suspect there is something in common about our system setups which is non-standard...

**Comment by jack4455667788** [comment]
> When does that happen? When logging in or creating an account on the menu? Or opening the Miiverse applet? Are you using Inkay from the releases tab or the bleeding edge build? Which commit (if you know)?

Using both the latest release (crc32 = A75067AC) and the nightly (https://nightly.link/PretendoNetwork/Inkay/actions/runs/8714756349/inkay.zip - crc32 = A475D88D).

This is whenever account login or game server access/connection is requested. I presume Miiverse applet as well - although I have not tested that.

**Comment by ashquarky** [comment]
> Sorry for the bad lead. Nimble does not function (except to cause wups, and hence MK8 Ultimate, to blackscreen) in tiramisu,

That's the problem with Tiramisu - we can't run several homebrew apps at once, thus we can't run Nimble and another homebrew at once - and if you're not going to run another homebrew, why use Tiramisu? So we just gave up on supporting it

> Could this be a legitimate CACERT SSL error? Your servers refusing an ssl connection from our consoles or vice versa?

My understanding of the CACERT error is that the console is rejecting our certs, which is weird because Inkay is supposed to disable verification entirely.

Hunch - do you know if you've rebuilt your NAND at all? NAND-AID or redNAND or usata or the like?

**Comment by jack4455667788** [comment]
> That's the problem with Tiramisu - we can't run several homebrew apps at once, thus we can't run Nimble and another homebrew at once - and if you're not going to run another homebrew, why use Tiramisu? So we just gave up on supporting it

True, but you can use wups (https://github.com/Maschell/WiiUPluginLoader) to do that in tiramisu.  I get that it is a pain to support/develop both, and perhaps one day everything will be ported over to aroma - but also, perhaps not :(

In my experience, wiimmfi was all about ctgp, and the only available (yet, admittedly buggy and closed+lost source) ctgp for the wii-u (mk8 ultimate) only works in tiramisu (relies on a wups plugin).

> My understanding of the CACERT error is that the console is rejecting our certs, which is weird because Inkay is supposed to disable verification entirely.

Something very weird is going on.
 
> Hunch - do you know if you've rebuilt your NAND at all? NAND-AID or redNAND or usata or the like?

I MAY have experimented with redNAND back in the day, as a lark. I can't remember now, it's been so long.  I've never rebuilt the nand or cracked open the case.

It is my understanding that the system cacerts are responsible for such ssl rejection/support.  If this is the case, could you please provide the crc of the working cacerts on the wiiu side so I can check them against mine?

They can be found in storage_mlc\sys\title\0005001b\10054000\content. My guess is the ccerts and scerts folders being the likely most relevant.

My other hunch is this is somehow related to the dual boot setup (which only allows use of the second to latest aroma), or the system ios version spoof.  Are the inkay patches ios version specific (i.e. patch specific addresses that change over ios revisions)?

Thanks for your help with this! I'd like to assist in any way i can to help get it sorted if possible.

**Comment by WizardNight7718** [comment]
> > That's the problem with Tiramisu - we can't run several homebrew apps at once, thus we can't run Nimble and another homebrew at once - and if you're not going to run another homebrew, why use Tiramisu? So we just gave up on supporting it
> 
> True, but you can use wups (https://github.com/Maschell/WiiUPluginLoader) to do that in tiramisu. I get that it is a pain to support/develop both, and perhaps one day everything will be ported over to aroma - but also, perhaps not :(
> 
> In my experience, wiimmfi was all about ctgp, and the only available (yet, admittedly buggy and closed+lost source) ctgp for the wii-u (mk8 ultimate) only works in tiramisu (relies on a wups plugin).
> 
> > My understanding of the CACERT error is that the console is rejecting our certs, which is weird because Inkay is supposed to disable verification entirely.
> 
> Something very weird is going on.
> 
> > Hunch - do you know if you've rebuilt your NAND at all? NAND-AID or redNAND or usata or the like?
> 
> I MAY have experimented with redNAND back in the day, as a lark. I can't remember now, it's been so long. I've never rebuilt the nand or cracked open the case.
> 
> It is my understanding that the system cacerts are responsible for such ssl rejection/support. If this is the case, could you please provide the crc of the working cacerts on the wiiu side so I can check them against mine?
> 
> They can be found in storage_mlc\sys\title\0005001b\10054000\content. My guess is the ccerts and scerts folders being the likely most relevant.
> 
> My other hunch is this is somehow related to the dual boot setup (which only allows use of the second to latest aroma), or the system ios version spoof. Are the inkay/nimble patches ios version specific (i.e. patch specific addresses that change over ios revisions)?
> 
> Thanks for your help with this! I'd like to assist in any way i can to help get it sorted if possible.

Which files in specific, do you need to make a side by side comparison?

**Comment by jack4455667788** [comment]
> Which files in specific, do you need to make a side by side comparison?

I'm not 100% sure. It partly depends on what certificate(s) pretendo is using on their side.

But assuming this IS a legitimate cacert error, then the general idea is to compare all of the certificates on our consoles (experiencing the 2160) against working consoles copies of the files.

The list of filenames most likely involved are below.

in the ccerts folder :

WIIU_ACCOUNT_1_CERT.der
WIIU_ACCOUNT_1_RSA_KEY.aes
WIIU_COMMON_1_CERT.der
WIIU_COMMON_1_RSA_KEY.aes
WIIU_OLIVE_1_CERT.der
WIIU_OLIVE_1_RSA_KEY.aes
WIIU_VINO_1_CERT.der
WIIU_VINO_1_RSA_KEY.aes
WIIU_WAGONU_CRYPTO_SYMKEY.aes
WIIU_WAGONU_HMAC_KEY.aes
WIIU_WOOD_1_CERT.der
WIIU_WOOD_1_RSA_KEY.aes

in the scerts folder :

ADDTRUST_EXT_CA_ROOT.der
AMAZON_ROOT_CA1.der
BALTIMORE_CYBERTRUST_ROOT_CA.der
CACERT_NINTENDO_CA.der
CACERT_NINTENDO_CA_G2.der
CACERT_NINTENDO_CA_G3.der
CACERT_NINTENDO_CLASS2_CA.der
CACERT_NINTENDO_CLASS2_CA_G2.der
CACERT_NINTENDO_CLASS2_CA_G3.der
COMODO_CA.der
COMODO_RSA_CA.der
CYBERTRUST_GLOBAL_ROOT_CA.der
DIGICERT_ASSURED_ID_ROOT_CA.der
DIGICERT_ASSURED_ID_ROOT_CA_G2.der
DIGICERT_GLOBAL_ROOT_CA.der
DIGICERT_GLOBAL_ROOT_CA_G2.der
DIGICERT_HIGH_ASSURANCE_EV_ROOT_CA.der
ENTRUST_CA_2048.der
ENTRUST_ROOT_CA.der
ENTRUST_ROOT_CA_G2.der
ENTRUST_SECURE_SERVER_CA.der
EQUIFAX_SECURE_CA.der
GEOTRUST_GLOBAL_CA.der
GEOTRUST_GLOBAL_CA2.der
GEOTRUST_PRIMARY_CA.der
GEOTRUST_PRIMARY_CA_G3.der
GLOBALSIGN_ROOT_CA.der
GLOBALSIGN_ROOT_CA_R2.der
GLOBALSIGN_ROOT_CA_R3.der
GTE_CYBERTRUST_GLOBAL_ROOT.der
NTD_DEV_CA.der
STARFIELD_SERVICES_ROOT_CERTIFICATE_AUTHORITY_G2.der
THAWTE_PREMIUM_SERVER_CA.der
THAWTE_PRIMARY_ROOT_CA.der
THAWTE_PRIMARY_ROOT_CA_G3.der
USERTRUST_RSA_CA.der
UTN_DATACORP_SGC_CA.der
UTN_USERFIRST_HARDWARE_CA.der
VERISIGN_CLASS3_PUBLIC_PRIMARY_CA.der
VERISIGN_CLASS3_PUBLIC_PRIMARY_CA_G2.der
VERISIGN_CLASS3_PUBLIC_PRIMARY_CA_G3.der
VERISIGN_CLASS3_PUBLIC_PRIMARY_CA_G5.der
VERISIGN_UNIVERSAL_ROOT_CA.der
VERIZON_GLOBAL_ROOT_CA.der

However, if ashquarky is right that inkay is supposed to disable ssl verification entirely (not a good idea) - then there is something else going on here and the checksums for our certs and those from working consoles will likely match.

**Comment by WizardNight7718** [comment]
[CERTS.zip](https://github.com/PretendoNetwork/Inkay/files/15049516/CERTS.zip)
Here are the certs for my console

**Comment by Eco-Gaming** [comment]
> > When does that happen? When logging in or creating an account on the menu? Or opening the Miiverse applet? Are you using Inkay from the releases tab or the bleeding edge build? Which commit (if you know)?
> 
> Using both the latest release (crc32 = A75067AC) and the nightly (https://nightly.link/PretendoNetwork/Inkay/actions/runs/8714756349/inkay.zip - crc32 = A475D88D).
> 
> This is whenever account login or game server access/connection is requested. I presume Miiverse applet as well - although I have not tested that.
> 
> Interestingly enough, using SSSL also causes the same error (internet connection test succeeds).
> 
> Could this be a legitimate CACERT SSL error? Your servers refusing an ssl connection from our consoles or vice versa?

I have the exact same issue (didn't check which version I'm on, I can do that tomorrow).

I'm not that familiar with WiiU modding, but my console has a broken NAND chip so I followed [this guide](https://gbatemp.net/threads/fixing-system-memory-error-160-0103-failing-emmc-without-soldering-using-rednand-with-isfshax.642268/) for using the SD card as NAND (I believe it uses rednand, at least that shows up during the boot sequence).

I can also provide my certs tomorrow if that helps.

**Comment by ashquarky** [comment]
> My other hunch is this is somehow related to the dual boot setup (which only allows use of the second to latest aroma), or the system ios version spoof. Are the inkay/nimble patches ios version specific (i.e. patch specific addresses that change over ios revisions)?

Yep, 5.5.4 and 5.5.5+ have different IOS versions and different patches. If you're spoofing, that would mix up Inkay and prevent the ssl patches from working.

**Comment by ashquarky** [comment]
> I'm not that familiar with WiiU modding, but my console has a broken NAND chip so I followed [this guide](https://gbatemp.net/threads/fixing-system-memory-error-160-0103-failing-emmc-without-soldering-using-rednand-with-isfshax.642268/) for using the SD card as NAND (I believe it uses rednand, at least that shows up during the boot sequence).

MLC rebuilding (as per that guide) can also lead to your ios version and your system version not matching up, which confuses Inkay. Sounds like we might need to improve Inkay's version detection if this is getting more common...

**Comment by WizardNight7718** [comment]
When I was transferring to the latest version for the wii u, it wouldn't let me update the regular way, so I originally downloaded the update and installed it manually, I don't exactly remember how I did that, that might've been the cause?

**Comment by WizardNight7718** [comment]
> When I was attempting to update to the latest version for the wii u, it wouldn't let me do it, so I originally downloaded the update and installed it manually, I don't exactly remember how I did that? Could that have been the cause?

If this was the cause, what could I do to fix it?

**Comment by ashquarky** [comment]
We probably have to fix it in Inkay, but I'm asking around for a workaround in the meantime

**Comment by ashquarky** [comment]
Try running a system update from Settings? when you rebuilt the MLC, *most* of your titles got updated to latest, but the SLC ones (including IOSU) are still outdated.

**Comment by WizardNight7718** [comment]
When attempting to update normally, it's says "Software is Up to Date"

**Comment by Eco-Gaming** [comment]
> Try running a system update from Settings? when you rebuilt the MLC, _most_ of your titles got updated to latest, but the SLC ones (including IOSU) are still outdated.
> 
> ![image](https://private-user-images.githubusercontent.com/8533313/324655446-299267cd-2f6b-45e5-8a70-5cb1e976329c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTgzNjIsIm5iZiI6MTcxMzg1ODA2MiwicGF0aCI6Ii84NTMzMzEzLzMyNDY1NTQ0Ni0yOTkyNjdjZC0yZjZiLTQ1ZTUtOGE3MC01Y2IxZTk3NjMyOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMDc0MTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc5ODYyM2RmOTRkNDk2YmE2MWIxZDRlMWY3ZTZkZGYzZDJlMmE3ZTFkNTQ3ZGM2ZmRiN2M5NWVjNWMxNGVjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PA0eBZXsk02gEaPcQsMtuUW8-FqC4ifm0daVaTVUdKU)

Ohhh in the Rebuilding MLC part I skipped the SLC files, as I just assumed my console was running a recent version. I'm going to try reinstalling from scratch and include SLC this time.

**Comment by jack4455667788** [comment]
> > My other hunch is this is somehow related to the dual boot setup (which only allows use of the second to latest aroma), or the system ios version spoof. Are the inkay/nimble patches ios version specific (i.e. patch specific addresses that change over ios revisions)?
> 
> Yep, 5.5.4 and 5.5.5+ have different IOS versions and different patches. If you're spoofing, that would mix up Inkay and prevent the ssl patches from working.

I am on 5.5.0 (spoofed to 5.5.6). Are the particular offsets and patches known for this version (i don't mind compiling a special version to share with others in my boat)?

Is there a table or list of the offsets and patches from the current and any previous IOS versions available (preferably including what the hex pre-patch would be)?

I don't like to fix what isn't broken, and flashing the firmware is always a risk - so I'd like to stay on 5.5.0 if possible.

**Comment by WizardNight7718** [comment]
We all have different situations that lead to the same error, so what did we do or "inkay" detect wrong?

**Comment by theDSi2homebrewGuy** [comment]
I fixed my issue, I just redownloaded the inkay and aroma files to my sd card.

**Comment by ashquarky** [comment]
Will test some alternative methods to detect the IOSU version to support this situation.

**Comment by ashquarky** [comment]
We need Inkay to be able to know the IOSU *build version* (v15702, v15848) somehow, and switch on that for the patches rather than using the system version (5.5.5/5.5.6 etc.) which can be spoofed or get desynced in a variety of ways.

Ideas for that:
 - `Mocha_IOSUKernelRead32` some value that is either the version number itself or some value that naturally differs between versions
 - Call some built-in API that gives the OSv10 build number (if it exists it'll be in coreinit)
 - Slurp the OSv10 meta.xml (ACPGetMetaXML?) - this is likely to be sloooow though

Opening it up for others' ideas and research.

**Comment by WizardNight7718** [comment]
Hopefully, we can get this resolved by the end of this year 🙏

**Comment by RamsesUTL** [comment]
I have the same issue after rebuilding my dead WiiU with NAND-Aid.

**Comment by RamsesUTL** [comment]
Any news on that matter? I hoped for a change with Inkay 3.0.0 but the problem remains.

**Comment by jonbarrow** [comment]
> We need Inkay to be able to know the IOSU build version (v15702, v15848) somehow, and switch on that for the patches rather than using the system version (5.5.5/5.5.6 etc.) which can be spoofed or get desynced in a variety of ways.

Genuine question; Is this something we should actually consider within the scope of Inkay? My understanding of this issue is that it's caused, mainly, by one of 2 reasons:

- A bad/incomplete NAND rebuild
- Spoofing your system version

The rebuild issue seems to already have a working fix, as indicated earlier in the thread? If the rebuild causes a version mismatch then that sounds like an actual issue that should be fixed by the user, rather than worked around by us imo, and for us to have some sort of warning or disclaimer somewhere about this issue and how to fix it on the users end. I think it's more than valid for us to have the expectation that a user is running a "typical" console (one that doesn't have weird mismatches like this)

As for the spoofing of versions, what exactly is the reason for that? Why not just update the console? I'm genuinely asking. I've only personally seen a handful of people who spoof their version, most of which being in this thread, so I'm not sure what the purpose is. It's not like newer versions are unable to be modded? I can see there being legitimate reasons to run older versions of *games* (such as downgrading Super Mario Maker to get the Miiverse functionality back) so it's valid that our per-game patches check the game version, but the only thing I can think of that would require a lower *firmware* would maybe be the TVii icon...? But even then, modern homebrew can add the icon back (the icon was just removed from the home menu, the title still exists on the latest firmware) and I've seen people downgrade just the menu title for this (even on latest FW). I'm not sure what the purpose is for trying to support older firmware, or why we're expected to, especially since it seems up in the air as to how we'd even detect that reliably/efficiently?
